name: Publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: "npm ci"
      
      - name: Publish documentation
        run: "npm run publish:docs"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish the package
        run: "npm run publish:package"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
